### ISSUE TITLE
Profile in production and send to grafana

### ISSUE THREAD

**Issue by kentcdodds** [kentcdodds/bookshelf#33]
In my performance workshop I show people how to do [React Production Performance Monitoring](https://kentcdodds.com/blog/react-production-performance-monitoring) and explain that you'd normally send the data to a monitoring tool like Grafana, but I think it would help a lot if they saw an example of this.

So I'd like to set that up for this app, but I don't know how to get that set up/host it/load in data/make charts/etc. Happy to use Netlify functions to interact with it (if I can't do so direct from the client).

Anyone wanna help with this? I'm very out of my element here 😬

**Comment by kentcdodds** [comment]
Here's an example of the kind of data that I'd be able to graph:


```javascript
{
  id: "Navigation",
  phase: "update",
  actualDuration: 0.09999994654208422,
  baseDuration: 0.3799999540206045,
  startTime: 104988.11499998556,
  commitTime: 104988.45000000438,
  interactions: [
    {
      __count: 0
      id: 3,
      name: "menu click",
      timestamp: 104978.33499999251,
    }
  ],
}
```

And here's a live example:

https://react-performance.netlify.app/isolated/final/07.extra-1.js

Click the button and checkout the console.

**Comment by puregarlic** [comment]
I'll lend a hand, although I'm probably out of my element as well 😅 

Before we get the data visualized on Grafana, we need to start by [storing it somewhere](https://grafana.com/docs/grafana/latest/features/datasources/). I'd suggest TimescaleDB since it's Postgres under the covers and fairly easy to get running.

Docker would make things easy to spin up for local testing and then deploy to a DO Droplet. From my limited industry knowledge, the process would look something like this:

1. Batch profiling data from React
2. Submit batched data to a Netlify function endpoint
3. Write the data to TimescaleDB running in Docker using the [`postgres`](https://www.npmjs.com/package/postgres) lib
4. Access the Grafana dashboard, also running in Docker, and then create/observe graphs there

From there, you at least have an interface to mess around with to create useful graphs.

Is that helpful? I can get a `docker-compose` config together if that would be useful.

**Comment by kentcdodds** [comment]
I don't want to bother getting this running locally. I'm fine mucking around and breaking things a bunch.

I can get points 1 and 2 working myself, but I don't have the bandwidth to go much further than that, so this may not actually happen 😅

**Comment by ckimrie** [comment]
As a learning resource I’m a little unclear on how much of this infrastructure problem you want to expose to students. So below I’m keeping things as simple as possible.

There are two parts to this, since Grafana only reads it from a data sources and doesn’t store anything itself.

- Grafana instance
- A Time series database to push your data into and for Grafana to read

Grafana supports several different data sources listed here: https://grafana.com/docs/grafana/latest/

Assuming you don’t want to run these locally (which is possible using Docker) you’ll need to setup paid version accessible on the internet.

## Grafana 

Absolute easiest way is to just pay for Grafana cloud: https://grafana.com/products/cloud/

It’s $49 a month and you get a managed Grafana plus a time series database included (Prometheus or graphite). This negates the secondary step of having to install and configure the DB.

Alternatively you can spin up a server image of Grafana using a cloud provider like AWS/Azure.  The Cloud Marketplaces typically have images good to go to allow spinning up in a couple of clicks (eg: AWS version https://aws.amazon.com/marketplace/pp/Bitnami-Grafana-Certified-by-Bitnami/B07JQ4LGF1)

This just gives you the Grafana instance, which then needs to connect to...

## Time series database

This is the harder one to setup purely due to choice paralysis.  Grafana’s big reason for existing is in order to work with loads of Time series databases.

If you aren’t familiar with databases or their setup, I’d say the _easiest_ of the Grafana options to just get going with is Elasticsearch, since it’s api is REST and with minimal setup you can just throw json at it and it’s very forgiving at just capturing it all while still allowing stats & aggregations on your data.

Easiest option here is Elastic cloud: https://www.elastic.co/cloud/

There’s a free trial, but for $16 you get a managed instance.

Similarly though, if you want the manual route, the cloud marketplaces have images that spin up quickly: https://aws.amazon.com/marketplace/pp/Bitnami-Elasticsearch-Certified-by-Bitnami/B00T6L24IU


# Follow up steps

With the above in place, it’s then a case of:

- Setup datasource in Grafana to pull data from the database
- Push data into the Time series database. This can be done from server side functions or direct from the browser depending on your auth & config requirements.
- Explore the data to Grafana
- Create charts & dashboard once you have a good feel for the data and statistical/aggregation needs (eg p99 duration aggregated per day)

**Comment by ckimrie** [comment]
I’m willing to help directly, but I’m based in London, so time zone means it’s end of day here and won’t be able to help immediately.  

Happy to get involved if your needs aren’t urgent though.

**Comment by puregarlic** [comment]
If you're not married to using Grafana, you could instead use [InfluxDB Cloud 2](https://www.influxdata.com/products/influxdb-cloud/), which has hosted, schema-less data storage _and_ graphs for free! That would also remove the need for Netlify functions, since you can use [their client library](https://github.com/influxdata/influxdb-client-js) and write data directly from the browser. It's fast to started with, although I haven't tried using their JS API before. It looks fairly simple to use, though.

**Comment by kentcdodds** [comment]
I'm not married to grafana. It's just that when I teach people how to set up the client-side for performance monitoring, they want to see an example of what these kinds of graphs would look like to make it sink in more.

There's not much urgency. And I don't have the bandwidth to really work on this much more than the client-side portion and the netlify function.

If anyone wants to work on any of the other bits of this that would be super appreciated by everyone who wants to learn about production performance monitoring of React apps :)

**Comment by kentcdodds** [comment]
InfluxDB looks interesting and definitely affordable. I don't expect this app to generate a whole lot of data and I don't mind spending a little bit of money on this.

**Comment by karlhadwen** [comment]
A good free alternative that is pretty easy to setup is Sumo Logic, you can just post an object to an end-point and then go into Sumo and setup fancy graphs. If you're worried about security (probably not as this is just a demonstration) you can send that data to a Node proxy that will then forward the data onto Sumo. 

A good example that I recommend is here: https://www.sumologic.com/blog/javascript-logging-sdk/ - it took me around 10 minutes to setup. Once you're setup, the charts are fairly simple to create, and the syntax is similar to SQL. I found Grafana a little tedious to setup when I first used it, but having looked for alternatives I came across Sumo and it works pretty well.

**Comment by kentcdodds** [comment]
Hey thanks @karlhadwen! That actually looks really great! Sounds like the simplest and cheapest solution so far. I think all I really want to do is show people a graph of time-series data to catch the vision of how this could be helpful.

I think I'll give that a look.

**Comment by ncesar** [comment]
I think the best solution would be to run grafana on a docker container and use https://github.com/bergquist/fake-simple-json-datasource
